config:
  registries:
    - name: ECR
      api_url: https://<account-id>.dkr.ecr.us-west-2.amazonaws.com
      prefix: <account-id>.dkr.ecr.us-west-2.amazonaws.com
      ping: yes
      insecure: no
      credentials: ext:/scripts/login.sh
      credsexpire: 6h

authScripts:
  enabled: true
  scripts:
      login.sh: |
        #!/bin/sh
        aws ecr --region "us-west-2" get-authorization-token --output text --query 'authorizationData[].authorizationToken' | base64 -d