replicaCount: 1

image:
  repository: 637423664276.dkr.ecr.us-west-2.amazonaws.com/flask-app
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 5000
  nodePort: 30050
